version: '3.7'

services: 
  app:
    hostname: golang_example_production
    container_name: golang_example_production
    depends_on: 
      - postgres
      - zookeeper
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
      target: prod
    environment: 
      SERVING_PORT: "*:8080"
      DB_HOST: golang_example_db
      DB_PORT: 5432
      DB_NAME: golang_example_db
      DB_USER: postgres
      DB_PASS: developer
      KAFKA_HOST_1: kafka_1:29092
      KAFKA_HOST_2: kafka_2:29093
      KAFKA_HOST_3: kafka_3:29094
      GIN_MODE: release
    ports:
      - 8080:8080
    command: bash -c "go mod download && go build -o /bin/app/build/main ./src && /bin/app/build/main"
    networks: 
      - kafka
      - golang_example_production

  postgres:
    image: postgres:11
    container_name: golang_example_db
    volumes:
      - golang_example_production:/var/libs/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=developer
      - POSTGRES_DB=golang_example_db
      - POSTGRES_PORT=5432
    ports:
      - 5432:5432
    networks: 
      - golang_example_production
  
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - 2181:2181
    environment: 
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks: 
      - kafka
  
  kafka_1:
    image: bitnami/kafka:latest
    container_name: kafka_1
    ports:
      - 29092:29092
      - 9092:9092
    environment: 
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka_1:9092,PLAINTEXT_HOST://kafka_1:29092
    depends_on: 
      - zookeeper
    networks: 
      - kafka
    
  kafka_2:
    image: bitnami/kafka:latest
    container_name: kafka_2
    ports:
      - 29093:29093
      - 9093:9092
    environment: 
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://:9093,PLAINTEXT_HOST://:29093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka_2:9093,PLAINTEXT_HOST://kafka_2:29093
    depends_on: 
      - zookeeper
    networks: 
      - kafka
    
  kafka_3:
    image: bitnami/kafka:latest
    container_name: kafka_3
    ports:
      - 29094:29094
      - 9094:9092
    environment: 
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://:9094,PLAINTEXT_HOST://:29094
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka_3:9094,PLAINTEXT_HOST://kafka_3:29094
    depends_on: 
      - zookeeper
    networks: 
      - kafka

volumes: 
  golang_example_production:

networks:
  kafka:
  golang_example_production: